name: pb_hrsystem
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_local_notifications: ^17.2.1+1
  permission_handler: ^11.3.1
  intl: any
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  table_calendar: ^3.1.2
  local_auth: ^2.2.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  responsive_framework: ^0.1.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.7
  intl_generator: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/logo.png
    - assets/notification_image.png
    - assets/location_image.png
    - assets/camera_image.png
    - assets/ready_image.png
    - assets/ready_bg.png
    - assets/home_banner.png
    - assets/profile_picture.png
    - assets/qr_code.png
    - assets/darkbg.png
    - assets/bg_2.png
    - assets/success_icon.png
    - assets/banner1.png
    - assets/banner2.png
    - assets/banner3.png
    - assets/flags/english.png
    - assets/flags/laos.png
    - assets/flags/chinese.png